title: generic-python-turtle-basics
hero_image: images/banner.png
description: generic-python-turtle-basics description
original_url: 
theme: cc-prototype
duration: 1 # 1, 2 or 3
listed: false
ingredient: true
interests: "graphics"
technologies: "python, turtle"
steps:
  - title: Turtle basics
